Traceback (most recent call last):
  File "C:\Users\F37YHCS\fixing\ecs_pull.py", line 80, in <module>
    pull_all_cluster_info(cluster_name)
  File "C:\Users\F37YHCS\fixing\ecs_pull.py", line 73, in pull_all_cluster_info
    services_info = get_cluster_info(cluster_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\F37YHCS\fixing\ecs_pull.py", line 30, in get_cluster_info
    json.dump(task_definition, task_file, indent=4)
  File "C:\Program Files\Python311\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
